### PR TITLE
fix(db:products): fix inclusion of camelCasing

### LINKED ISSUE #43: db product fix
fixing certain namings within the db

### PR DESCRIPTION
**Pull request by juscuzryancan**
Fixes #43 needed to change the quotation marks on certain tables

### CODE REVIEW

File: db/init_db.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ async function buildTables() {
       firstName VARCHAR(255) NOT NULL,
```
Comment (bboysamuel) [inline db/init_db.js]:
```suggestion
      "firstName" VARCHAR(255) NOT NULL,
```

File: db/init_db.js [hunk 2]
```diff
@@ -21,7 +21,7 @@ async function buildTables() {
...
       lastName VARCHAR(255) NOT NULL,
```
Comment (bboysamuel) [inline db/init_db.js]:
```suggestion
      "lastName" VARCHAR(255) NOT NULL,
```

**Review by bboysamuel — APPROVED** [review]
updated camelCasing quotes on last name and firstname
